### ISSUE TITLE
Tarea 65- Crear una incidencia intentando conectarse a la aplicación en periodos no disponibles (Cada miembro).

### ISSUE THREAD

**Issue by NoSoyDani** [gii-is-psg2/PSG2-2021-G3-31#94]
Daniel Muñoz Heredia - [X]
Francisco Villazán Torres - [X]
Daniel Toro Valle - [X]
Badayco Rijo Hernández - [X]
Daniel Suárez Perea - [X]
Manuel Muñoz España - [X]

**Comment by fraviltor** [comment]
Todos los miembros han creado correctamente las incidencias en periodos no disponibles.
