### ISSUE TITLE
Tarea 69-  Extender el informe técnico "SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G3-31".

### ISSUE THREAD

**Issue by NoSoyDani** [gii-is-psg2/PSG2-2021-G3-31#99]
Análisis de los problemas anteriores S2 y S3.
Dicho análisis debe contener una tabla donde, para cada tema, especificas si se cumple o no el SLT descrito en tu SLA, y unas conclusiones finales analizando los resultados globales.

**Comment by manmunesp12** [comment]
Se ha realizado correctamente la extensión extra.
